### ISSUE TITLE
Wallet TX Fee is not being 0.01, is being 0.1 instead.

### ISSUE THREAD

**Issue by emedrano2112** [pokt-foundation/explorer#95] opened 2020-11-11 16:29 UTC
When sending a normal TX using the wallet, it was noticed that instead of 0.01, it was costing 0.1.
<img width="655" alt="Screen Shot 2020-11-11 at 13 29 12" src="https://user-images.githubusercontent.com/17748171/98837606-eafe7f00-2421-11eb-855c-088fb7d335fa.png">

**Comment by pabelnl** [comment] 2020-11-18 21:08
The wrong repository, the issue is already fixed in the Wallet.

**Closed as completed by pabelnl** 2020-11-18 21:08 UTC
